package aplikasirental.gui;

import aplikasirental.manager.*;
import aplikasirental.model.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.List;

/**
 * CustomerPanel - Form untuk manajemen pelanggan
 * 
 * @author AplikasiRental
 */
public class CustomerPanel extends javax.swing.JPanel {
    private CustomerManager customerManager;
    private DefaultTableModel customerTableModel;
    private JFrame parentFrame;
    
    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        setupTableModel();
    }
    
    public CustomerPanel(JFrame parentFrame, CustomerManager customerManager) {
        this.parentFrame = parentFrame;
        this.customerManager = customerManager;
        initComponents();
        setupTableModel();
    }
    
    private void setupTableModel() {
        // Get the existing model from the table (already configured by initComponents)
        customerTableModel = (DefaultTableModel) customerTable.getModel();
        customerTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void refreshTable() {
        if (customerTableModel == null || customerManager == null) return;
        customerTableModel.setRowCount(0);
        List<Customer> customers = customerManager.getAllCustomers();
        for (Customer c : customers) {
            Object[] row = {
                c.getCustomerId(),
                c.getName(),
                c.getPhoneNumber(),
                c.getAddress(),
                c.getIdNumber()
            };
            customerTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Manajemen Pelanggan");

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No. Telepon", "Alamat", "No. KTP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        btnTambah.setText("Tambah Pelanggan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Pelanggan");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Pelanggan");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showAddCustomerDialog();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        showEditCustomerDialog();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void showAddCustomerDialog() {
        if (parentFrame == null || customerManager == null) return;
        
        JDialog dialog = new JDialog(parentFrame, "Tambah Pelanggan", true);
        dialog.setLayout(new BorderLayout(10, 10));
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(parentFrame);
        
        JPanel formPanel = new JPanel(new GridLayout(0, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        formPanel.add(new JLabel("ID Pelanggan:"));
        JTextField idField = new JTextField(customerManager.generateCustomerId());
        idField.setEditable(false);
        formPanel.add(idField);
        
        formPanel.add(new JLabel("Nama:"));
        JTextField nameField = new JTextField();
        formPanel.add(nameField);
        
        formPanel.add(new JLabel("No. Telepon:"));
        JTextField phoneField = new JTextField();
        formPanel.add(phoneField);
        
        formPanel.add(new JLabel("Alamat:"));
        JTextField addressField = new JTextField();
        formPanel.add(addressField);
        
        formPanel.add(new JLabel("No. KTP:"));
        JTextField idNumberField = new JTextField();
        formPanel.add(idNumberField);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton saveButton = new JButton("Simpan");
        saveButton.addActionListener(e -> {
            String id = idField.getText();
            String name = nameField.getText();
            String phone = phoneField.getText();
            String address = addressField.getText();
            String idNumber = idNumberField.getText();
            
            if (name.isEmpty() || phone.isEmpty() || address.isEmpty() || idNumber.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Customer customer = new Customer(id, name, phone, address, idNumber);
            customerManager.addCustomer(customer);
            refreshTable();
            dialog.dispose();
            JOptionPane.showMessageDialog(parentFrame, "Pelanggan berhasil ditambahkan!");
        });
        buttonPanel.add(saveButton);
        
        JButton cancelButton = new JButton("Batal");
        cancelButton.addActionListener(e -> dialog.dispose());
        buttonPanel.add(cancelButton);
        
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    private void showEditCustomerDialog() {
        if (parentFrame == null || customerManager == null) return;
        
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih pelanggan yang akan diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Customer customer = customerManager.getAllCustomers().get(selectedRow);
        
        JDialog dialog = new JDialog(parentFrame, "Edit Pelanggan", true);
        dialog.setLayout(new BorderLayout(10, 10));
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(parentFrame);
        
        JPanel formPanel = new JPanel(new GridLayout(0, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        formPanel.add(new JLabel("ID Pelanggan:"));
        JTextField idField = new JTextField(customer.getCustomerId());
        idField.setEditable(false);
        formPanel.add(idField);
        
        formPanel.add(new JLabel("Nama:"));
        JTextField nameField = new JTextField(customer.getName());
        formPanel.add(nameField);
        
        formPanel.add(new JLabel("No. Telepon:"));
        JTextField phoneField = new JTextField(customer.getPhoneNumber());
        formPanel.add(phoneField);
        
        formPanel.add(new JLabel("Alamat:"));
        JTextField addressField = new JTextField(customer.getAddress());
        formPanel.add(addressField);
        
        formPanel.add(new JLabel("No. KTP:"));
        JTextField idNumberField = new JTextField(customer.getIdNumber());
        formPanel.add(idNumberField);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton saveButton = new JButton("Simpan");
        saveButton.addActionListener(e -> {
            customer.setName(nameField.getText());
            customer.setPhoneNumber(phoneField.getText());
            customer.setAddress(addressField.getText());
            customer.setIdNumber(idNumberField.getText());
            
            customerManager.updateCustomer(selectedRow, customer);
            refreshTable();
            dialog.dispose();
            JOptionPane.showMessageDialog(parentFrame, "Pelanggan berhasil diupdate!");
        });
        buttonPanel.add(saveButton);
        
        JButton cancelButton = new JButton("Batal");
        cancelButton.addActionListener(e -> dialog.dispose());
        buttonPanel.add(cancelButton);
        
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    private void deleteCustomer() {
        if (parentFrame == null || customerManager == null) return;
        
        int selectedRow = customerTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih pelanggan yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(parentFrame, "Apakah Anda yakin ingin menghapus pelanggan ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            customerManager.deleteCustomer(selectedRow);
            refreshTable();
            JOptionPane.showMessageDialog(parentFrame, "Pelanggan berhasil dihapus!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
