package aplikasirental.gui;

import aplikasirental.manager.*;
import aplikasirental.model.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.List;

/**
 * RentalPanel - Form untuk manajemen transaksi rental
 * 
 * @author AplikasiRental
 */
public class RentalPanel extends javax.swing.JPanel {
    private RentalManager rentalManager;
    private VehicleManager vehicleManager;
    private CustomerManager customerManager;
    private DefaultTableModel rentalTableModel;
    private JFrame parentFrame;
    private Runnable onRentalChanged;
    
    /**
     * Creates new form RentalPanel
     */
    public RentalPanel() {
        initComponents();
        setupTableModel();
    }
    
    public RentalPanel(JFrame parentFrame, RentalManager rentalManager, VehicleManager vehicleManager, CustomerManager customerManager) {
        this.parentFrame = parentFrame;
        this.rentalManager = rentalManager;
        this.vehicleManager = vehicleManager;
        this.customerManager = customerManager;
        initComponents();
        setupTableModel();
    }
    
    private void setupTableModel() {
        // Get the existing model from the table (already configured by initComponents)
        rentalTableModel = (DefaultTableModel) rentalTable.getModel();
        rentalTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setOnRentalChanged(Runnable callback) {
        this.onRentalChanged = callback;
    }
    
    private void notifyRentalChanged() {
        if (onRentalChanged != null) {
            onRentalChanged.run();
        }
    }
    
    public void refreshTable() {
        if (rentalTableModel == null || rentalManager == null) return;
        rentalTableModel.setRowCount(0);
        List<Rental> rentals = rentalManager.getAllRentals();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (Rental r : rentals) {
            Object[] row = {
                r.getRentalId(),
                r.getCustomer().getName(),
                r.getVehicle().getBrand() + " " + r.getVehicle().getModel(),
                sdf.format(r.getStartDate()),
                sdf.format(r.getEndDate()),
                r.getDays(),
                String.format("Rp %.0f", r.getTotalCost()),
                r.getStatus()
            };
            rentalTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentalTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnRentalBaru = new javax.swing.JButton();
        btnSelesaikan = new javax.swing.JButton();
        btnBatalkan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Transaksi Rental");

        rentalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Rental", "Pelanggan", "Kendaraan", "Tgl Mulai", "Tgl Selesai", "Hari", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rentalTable);

        btnRentalBaru.setText("Rental Baru");
        btnRentalBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalBaruActionPerformed(evt);
            }
        });

        btnSelesaikan.setText("Selesaikan Rental");
        btnSelesaikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaikanActionPerformed(evt);
            }
        });

        btnBatalkan.setText("Batalkan Rental");
        btnBatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalkanActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnRentalBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelesaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBatalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRentalBaru)
                    .addComponent(btnSelesaikan)
                    .addComponent(btnBatalkan)
                    .addComponent(btnRefresh))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentalBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalBaruActionPerformed
        showAddRentalDialog();
    }//GEN-LAST:event_btnRentalBaruActionPerformed

    private void btnSelesaikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaikanActionPerformed
        completeRental();
    }//GEN-LAST:event_btnSelesaikanActionPerformed

    private void btnBatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalkanActionPerformed
        cancelRental();
    }//GEN-LAST:event_btnBatalkanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void showAddRentalDialog() {
        if (parentFrame == null || rentalManager == null || vehicleManager == null || customerManager == null) return;
        
        List<Customer> customers = customerManager.getAllCustomers();
        List<Vehicle> availableVehicles = vehicleManager.getAvailableVehicles();
        
        if (customers.isEmpty()) {
            JOptionPane.showMessageDialog(parentFrame, "Belum ada pelanggan terdaftar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (availableVehicles.isEmpty()) {
            JOptionPane.showMessageDialog(parentFrame, "Tidak ada kendaraan yang tersedia!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        JDialog dialog = new JDialog(parentFrame, "Rental Baru", true);
        dialog.setLayout(new BorderLayout(10, 10));
        dialog.setSize(500, 400);
        dialog.setLocationRelativeTo(parentFrame);
        
        JPanel formPanel = new JPanel(new GridLayout(0, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        formPanel.add(new JLabel("ID Rental:"));
        JTextField idField = new JTextField(rentalManager.generateRentalId());
        idField.setEditable(false);
        formPanel.add(idField);
        
        formPanel.add(new JLabel("Pelanggan:"));
        JComboBox<Customer> customerCombo = new JComboBox<>(customers.toArray(new Customer[0]));
        formPanel.add(customerCombo);
        
        formPanel.add(new JLabel("Kendaraan:"));
        JComboBox<Vehicle> vehicleCombo = new JComboBox<>(availableVehicles.toArray(new Vehicle[0]));
        formPanel.add(vehicleCombo);
        
        formPanel.add(new JLabel("Tanggal Mulai:"));
        JTextField startDateField = new JTextField(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        formPanel.add(startDateField);
        
        formPanel.add(new JLabel("Jumlah Hari:"));
        JTextField daysField = new JTextField("1");
        formPanel.add(daysField);
        
        formPanel.add(new JLabel("Total Biaya:"));
        JTextField totalField = new JTextField("0");
        totalField.setEditable(false);
        formPanel.add(totalField);
        
        // Calculate total on changes
        ActionListener calculateTotal = e -> {
            try {
                int days = Integer.parseInt(daysField.getText());
                Vehicle selected = (Vehicle) vehicleCombo.getSelectedItem();
                if (selected != null) {
                    double total = days * selected.getDailyRate();
                    totalField.setText(String.format("Rp %.0f", total));
                }
            } catch (NumberFormatException ex) {
                totalField.setText("0");
            }
        };
        
        daysField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                calculateTotal.actionPerformed(null);
            }
        });
        vehicleCombo.addActionListener(calculateTotal);
        calculateTotal.actionPerformed(null);
        
        dialog.add(formPanel, BorderLayout.CENTER);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton saveButton = new JButton("Simpan");
        saveButton.addActionListener(e -> {
            try {
                String id = idField.getText();
                Customer customer = (Customer) customerCombo.getSelectedItem();
                Vehicle vehicle = (Vehicle) vehicleCombo.getSelectedItem();
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date startDate = sdf.parse(startDateField.getText());
                int days = Integer.parseInt(daysField.getText());
                
                Calendar cal = Calendar.getInstance();
                cal.setTime(startDate);
                cal.add(Calendar.DAY_OF_MONTH, days);
                Date endDate = cal.getTime();
                
                Rental rental = new Rental(id, customer, vehicle, startDate, endDate, days);
                rentalManager.addRental(rental);
                refreshTable();
                notifyRentalChanged();
                dialog.dispose();
                JOptionPane.showMessageDialog(parentFrame, "Rental berhasil ditambahkan!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        buttonPanel.add(saveButton);
        
        JButton cancelButton = new JButton("Batal");
        cancelButton.addActionListener(e -> dialog.dispose());
        buttonPanel.add(cancelButton);
        
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    private void completeRental() {
        if (parentFrame == null || rentalManager == null) return;
        
        int selectedRow = rentalTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih rental yang akan diselesaikan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Rental rental = rentalManager.getAllRentals().get(selectedRow);
        if (!rental.getStatus().equals("Aktif")) {
            JOptionPane.showMessageDialog(parentFrame, "Rental ini sudah tidak aktif!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(parentFrame, "Selesaikan rental ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            rentalManager.completeRental(selectedRow);
            refreshTable();
            notifyRentalChanged();
            JOptionPane.showMessageDialog(parentFrame, "Rental berhasil diselesaikan!");
        }
    }
    
    private void cancelRental() {
        if (parentFrame == null || rentalManager == null) return;
        
        int selectedRow = rentalTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih rental yang akan dibatalkan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Rental rental = rentalManager.getAllRentals().get(selectedRow);
        if (!rental.getStatus().equals("Aktif")) {
            JOptionPane.showMessageDialog(parentFrame, "Rental ini sudah tidak aktif!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(parentFrame, "Batalkan rental ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            rentalManager.cancelRental(selectedRow);
            refreshTable();
            notifyRentalChanged();
            JOptionPane.showMessageDialog(parentFrame, "Rental berhasil dibatalkan!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalkan;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRentalBaru;
    private javax.swing.JButton btnSelesaikan;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rentalTable;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
