package aplikasirental.gui;

import aplikasirental.manager.*;
import aplikasirental.model.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * ReportPanel - Form untuk laporan statistik rental
 * 
 * @author AplikasiRental
 */
public class ReportPanel extends javax.swing.JPanel {
    private VehicleManager vehicleManager;
    private CustomerManager customerManager;
    private RentalManager rentalManager;
    private JFrame parentFrame;
    
    /**
     * Creates new form ReportPanel
     */
    public ReportPanel() {
        initComponents();
    }
    
    public ReportPanel(JFrame parentFrame, VehicleManager vehicleManager, CustomerManager customerManager, RentalManager rentalManager) {
        this.parentFrame = parentFrame;
        this.vehicleManager = vehicleManager;
        this.customerManager = customerManager;
        this.rentalManager = rentalManager;
        initComponents();
    }
    
    public void refreshReport() {
        if (vehicleManager == null || customerManager == null || rentalManager == null) return;
        
        StringBuilder sb = new StringBuilder();
        sb.append("=== LAPORAN APLIKASI RENTAL KENDARAAN ===\n\n");
        
        List<Vehicle> vehicles = vehicleManager.getAllVehicles();
        List<Customer> customers = customerManager.getAllCustomers();
        List<Rental> rentals = rentalManager.getAllRentals();
        List<Rental> activeRentals = rentalManager.getActiveRentals();
        
        sb.append("Total Kendaraan: ").append(vehicles.size()).append("\n");
        long availableVehicles = vehicles.stream().filter(Vehicle::isAvailable).count();
        sb.append("Kendaraan Tersedia: ").append(availableVehicles).append("\n");
        sb.append("Kendaraan Disewa: ").append(vehicles.size() - availableVehicles).append("\n\n");
        
        sb.append("Total Pelanggan: ").append(customers.size()).append("\n\n");
        
        sb.append("Total Transaksi Rental: ").append(rentals.size()).append("\n");
        sb.append("Rental Aktif: ").append(activeRentals.size()).append("\n");
        
        long completedRentals = rentals.stream()
            .filter(r -> r.getStatus().equals("Selesai"))
            .count();
        sb.append("Rental Selesai: ").append(completedRentals).append("\n");
        
        long cancelledRentals = rentals.stream()
            .filter(r -> r.getStatus().equals("Dibatalkan"))
            .count();
        sb.append("Rental Dibatalkan: ").append(cancelledRentals).append("\n\n");
        
        double totalRevenue = rentalManager.getTotalRevenue();
        sb.append(String.format("Total Pendapatan: Rp %.0f\n", totalRevenue));
        
        reportArea.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Laporan");

        reportArea.setEditable(false);
        reportArea.setColumns(20);
        reportArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        reportArea.setRows(5);
        jScrollPane1.setViewportView(reportArea);

        btnRefresh.setText("Refresh Laporan");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnRefresh)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshReport();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
