package aplikasirental.gui;

import aplikasirental.manager.*;
import aplikasirental.model.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.List;

/**
 * VehiclePanel - Form untuk manajemen kendaraan
 * 
 * @author AplikasiRental
 */
public class VehiclePanel extends javax.swing.JPanel {
    private VehicleManager vehicleManager;
    private DefaultTableModel vehicleTableModel;
    private JFrame parentFrame;
    
    /**
     * Creates new form VehiclePanel
     */
    public VehiclePanel() {
        initComponents();
        setupTableModel();
    }
    
    public VehiclePanel(JFrame parentFrame, VehicleManager vehicleManager) {
        this.parentFrame = parentFrame;
        this.vehicleManager = vehicleManager;
        initComponents();
        setupTableModel();
    }
    
    private void setupTableModel() {
        // Get the existing model from the table (already configured by initComponents)
        vehicleTableModel = (DefaultTableModel) vehicleTable.getModel();
        vehicleTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void refreshTable() {
        if (vehicleTableModel == null || vehicleManager == null) return;
        vehicleTableModel.setRowCount(0);
        List<Vehicle> vehicles = vehicleManager.getAllVehicles();
        for (Vehicle v : vehicles) {
            Object[] row = {
                v.getVehicleId(),
                v.getBrand(),
                v.getModel(),
                v.getYear(),
                v.getLicensePlate(),
                v.getVehicleType(),
                v.getKondisi() != null ? v.getKondisi() : "Baik",
                v.getKeterangan() != null ? v.getKeterangan() : "",
                String.format("Rp %.0f", v.getDailyRate()),
                v.isAvailable() ? "Tersedia" : "Disewa"
            };
            vehicleTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Manajemen Kendaraan");

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Merk", "Model", "Tahun", "Plat Nomor", "Tipe", "Kondisi", "Keterangan", "Tarif/Hari", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vehicleTable);

        btnTambah.setText("Tambah Kendaraan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Kendaraan");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Kendaraan");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showAddVehicleDialog();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        showEditVehicleDialog();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteVehicle();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refreshTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void showAddVehicleDialog() {
        if (parentFrame == null || vehicleManager == null) return;
        
        JDialog dialog = new JDialog(parentFrame, "Tambah Kendaraan", true);
        dialog.setLayout(new BorderLayout(10, 10));
        dialog.setSize(500, 450);
        dialog.setLocationRelativeTo(parentFrame);
        
        JPanel formPanel = new JPanel(new GridLayout(0, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Vehicle Type
        formPanel.add(new JLabel("Tipe Kendaraan:"));
        JComboBox<String> typeCombo = new JComboBox<>(new String[]{"Mobil", "Motor"});
        formPanel.add(typeCombo);
        
        // Basic Fields
        formPanel.add(new JLabel("ID Kendaraan:"));
        JTextField idField = new JTextField(vehicleManager.generateVehicleId());
        idField.setEditable(false);
        formPanel.add(idField);
        
        formPanel.add(new JLabel("Merk:"));
        JTextField brandField = new JTextField();
        formPanel.add(brandField);
        
        formPanel.add(new JLabel("Model:"));
        JTextField modelField = new JTextField();
        formPanel.add(modelField);
        
        formPanel.add(new JLabel("Tahun:"));
        JTextField yearField = new JTextField();
        formPanel.add(yearField);
        
        formPanel.add(new JLabel("Plat Nomor:"));
        JTextField plateField = new JTextField();
        formPanel.add(plateField);
        
        formPanel.add(new JLabel("Tarif Harian (Rp):"));
        JTextField rateField = new JTextField();
        formPanel.add(rateField);
        
        formPanel.add(new JLabel("Kondisi:"));
        JComboBox<String> kondisiCombo = new JComboBox<>(new String[]{"Sangat Baik", "Baik", "Cukup", "Perlu Perbaikan"});
        formPanel.add(kondisiCombo);
        
        formPanel.add(new JLabel("Keterangan:"));
        JTextField keteranganField = new JTextField();
        formPanel.add(keteranganField);
        
        // Car-specific fields
        JLabel doorsLabel = new JLabel("Jumlah Pintu:");
        JTextField doorsField = new JTextField();
        formPanel.add(doorsLabel);
        formPanel.add(doorsField);
        
        JLabel transLabel = new JLabel("Transmisi:");
        JComboBox<String> transCombo = new JComboBox<>(new String[]{"Manual", "Otomatis"});
        formPanel.add(transLabel);
        formPanel.add(transCombo);
        
        // Motorcycle-specific fields
        JLabel engineLabel = new JLabel("Kapasitas Mesin (cc):");
        JTextField engineField = new JTextField();
        engineLabel.setVisible(false);
        engineField.setVisible(false);
        formPanel.add(engineLabel);
        formPanel.add(engineField);
        
        JLabel motoTypeLabel = new JLabel("Tipe Motor:");
        JComboBox<String> motoTypeCombo = new JComboBox<>(new String[]{"Matic", "Sport", "Bebek"});
        motoTypeLabel.setVisible(false);
        motoTypeCombo.setVisible(false);
        formPanel.add(motoTypeLabel);
        formPanel.add(motoTypeCombo);
        
        // Type change listener
        typeCombo.addActionListener(e -> {
            boolean isCar = typeCombo.getSelectedItem().equals("Mobil");
            doorsLabel.setVisible(isCar);
            doorsField.setVisible(isCar);
            transLabel.setVisible(isCar);
            transCombo.setVisible(isCar);
            engineLabel.setVisible(!isCar);
            engineField.setVisible(!isCar);
            motoTypeLabel.setVisible(!isCar);
            motoTypeCombo.setVisible(!isCar);
        });
        
        dialog.add(formPanel, BorderLayout.CENTER);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton saveButton = new JButton("Simpan");
        saveButton.addActionListener(e -> {
            try {
                String id = idField.getText();
                String brand = brandField.getText();
                String model = modelField.getText();
                int year = Integer.parseInt(yearField.getText());
                String plate = plateField.getText();
                double rate = Double.parseDouble(rateField.getText());
                String kondisi = (String) kondisiCombo.getSelectedItem();
                String keterangan = keteranganField.getText();
                
                if (brand.isEmpty() || model.isEmpty() || plate.isEmpty()) {
                    JOptionPane.showMessageDialog(dialog, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                Vehicle vehicle;
                if (typeCombo.getSelectedItem().equals("Mobil")) {
                    int doors = Integer.parseInt(doorsField.getText());
                    String trans = (String) transCombo.getSelectedItem();
                    vehicle = new Car(id, brand, model, year, plate, rate, kondisi, keterangan, doors, trans);
                } else {
                    int engine = Integer.parseInt(engineField.getText());
                    String motoType = (String) motoTypeCombo.getSelectedItem();
                    vehicle = new Motorcycle(id, brand, model, year, plate, rate, kondisi, keterangan, engine, motoType);
                }
                
                vehicleManager.addVehicle(vehicle);
                refreshTable();
                dialog.dispose();
                JOptionPane.showMessageDialog(parentFrame, "Kendaraan berhasil ditambahkan!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Format angka tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        buttonPanel.add(saveButton);
        
        JButton cancelButton = new JButton("Batal");
        cancelButton.addActionListener(e -> dialog.dispose());
        buttonPanel.add(cancelButton);
        
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    private void showEditVehicleDialog() {
        if (parentFrame == null || vehicleManager == null) return;
        
        int selectedRow = vehicleTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih kendaraan yang akan diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Vehicle vehicle = vehicleManager.getAllVehicles().get(selectedRow);
        
        JDialog dialog = new JDialog(parentFrame, "Edit Kendaraan", true);
        dialog.setLayout(new BorderLayout(10, 10));
        dialog.setSize(500, 400);
        dialog.setLocationRelativeTo(parentFrame);
        
        JPanel formPanel = new JPanel(new GridLayout(0, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        formPanel.add(new JLabel("ID Kendaraan:"));
        JTextField idField = new JTextField(vehicle.getVehicleId());
        idField.setEditable(false);
        formPanel.add(idField);
        
        formPanel.add(new JLabel("Merk:"));
        JTextField brandField = new JTextField(vehicle.getBrand());
        formPanel.add(brandField);
        
        formPanel.add(new JLabel("Model:"));
        JTextField modelField = new JTextField(vehicle.getModel());
        formPanel.add(modelField);
        
        formPanel.add(new JLabel("Tahun:"));
        JTextField yearField = new JTextField(String.valueOf(vehicle.getYear()));
        formPanel.add(yearField);
        
        formPanel.add(new JLabel("Plat Nomor:"));
        JTextField plateField = new JTextField(vehicle.getLicensePlate());
        formPanel.add(plateField);
        
        formPanel.add(new JLabel("Tarif Harian (Rp):"));
        JTextField rateField = new JTextField(String.valueOf(vehicle.getDailyRate()));
        formPanel.add(rateField);
        
        formPanel.add(new JLabel("Kondisi:"));
        JComboBox<String> kondisiCombo = new JComboBox<>(new String[]{"Sangat Baik", "Baik", "Cukup", "Perlu Perbaikan"});
        kondisiCombo.setSelectedItem(vehicle.getKondisi() != null ? vehicle.getKondisi() : "Baik");
        formPanel.add(kondisiCombo);
        
        formPanel.add(new JLabel("Keterangan:"));
        JTextField keteranganField = new JTextField(vehicle.getKeterangan() != null ? vehicle.getKeterangan() : "");
        formPanel.add(keteranganField);
        
        if (vehicle instanceof Car) {
            Car car = (Car) vehicle;
            formPanel.add(new JLabel("Jumlah Pintu:"));
            JTextField doorsField = new JTextField(String.valueOf(car.getNumberOfDoors()));
            formPanel.add(doorsField);
            
            formPanel.add(new JLabel("Transmisi:"));
            JComboBox<String> transCombo = new JComboBox<>(new String[]{"Manual", "Otomatis"});
            transCombo.setSelectedItem(car.getTransmissionType());
            formPanel.add(transCombo);
        } else if (vehicle instanceof Motorcycle) {
            Motorcycle moto = (Motorcycle) vehicle;
            formPanel.add(new JLabel("Kapasitas Mesin (cc):"));
            JTextField engineField = new JTextField(String.valueOf(moto.getEngineCapacity()));
            formPanel.add(engineField);
            
            formPanel.add(new JLabel("Tipe Motor:"));
            JComboBox<String> motoTypeCombo = new JComboBox<>(new String[]{"Matic", "Sport", "Bebek"});
            motoTypeCombo.setSelectedItem(moto.getMotorcycleType());
            formPanel.add(motoTypeCombo);
        }
        
        dialog.add(formPanel, BorderLayout.CENTER);
        
        // Buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton saveButton = new JButton("Simpan");
        saveButton.addActionListener(e -> {
            try {
                vehicle.setBrand(brandField.getText());
                vehicle.setModel(modelField.getText());
                vehicle.setYear(Integer.parseInt(yearField.getText()));
                vehicle.setLicensePlate(plateField.getText());
                vehicle.setDailyRate(Double.parseDouble(rateField.getText()));
                vehicle.setKondisi((String) kondisiCombo.getSelectedItem());
                vehicle.setKeterangan(keteranganField.getText());
                
                vehicleManager.updateVehicle(selectedRow, vehicle);
                refreshTable();
                dialog.dispose();
                JOptionPane.showMessageDialog(parentFrame, "Kendaraan berhasil diupdate!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Format angka tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        buttonPanel.add(saveButton);
        
        JButton cancelButton = new JButton("Batal");
        cancelButton.addActionListener(e -> dialog.dispose());
        buttonPanel.add(cancelButton);
        
        dialog.add(buttonPanel, BorderLayout.SOUTH);
        dialog.setVisible(true);
    }
    
    private void deleteVehicle() {
        if (parentFrame == null || vehicleManager == null) return;
        
        int selectedRow = vehicleTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(parentFrame, "Pilih kendaraan yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(parentFrame, "Apakah Anda yakin ingin menghapus kendaraan ini?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            vehicleManager.deleteVehicle(selectedRow);
            refreshTable();
            JOptionPane.showMessageDialog(parentFrame, "Kendaraan berhasil dihapus!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables
}
